apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-generic-deployment.fullname" . }}
  labels:
    {{- include "helm-generic-deployment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- range $.Values.service.ports }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort | default "http" | quote }}
      protocol: {{ .protocol | default "tcp" | quote }}
      {{- if .name }}
      name: {{ .name | quote }}
      {{- end }}
  {{- end }}
  selector:
    {{- include "helm-generic-deployment.selectorLabels" . | nindent 4 }}
